.TH _PRINTF 3 "22 July 2025" "Custom Version" "Programmer's Manual"

.SH NAME
.B _printf

.SH SYNOPSIS
.B #include """main.h""

.B int _printf(const char *format, ...);

.SH DESCRIPTION
.B _printf

is a simplified implementation of the standard printf function.
It displays data to the standard output using a format string.
Each conversion specification is introduced
by the character %, and ends with a conversion specifier.

Supported format specifiers include:
.TP
.B %c
Prints a single character.

.TP
.B %s
Prints a string of characters.

.TP
.B %d
Prints a decimal integer.

.TP
.B %i
Prints a decimal or hexadecimal integer.

.TP
.B %%
Prints a literal percent sign.

if an invalid format specifier is encountered, 
both the `%` and the following character are printed as-is.

.SH RETURN VALUE
Return the total number of characters printed to the output (excluded null bytes)
return -1 if it is an error
.SH EXAMPLES
.nf
_printf("Hello %s! You scored %d%% on the test.\n", "Alice", 95);
.fi
Output:
.in
Hello Alice! You scored 95% on the test.

_printf("%cello, our names are %s and %s, we have respectively %d and %i years.\n", 'H', "Le Guen", "Leroy", 37, 17);
.fi
Output:
.in
Hello, our names are Le Guen and Leroy, we have respectively 37 and 17 years.

.SH SEE ALSO
.BR printf(3)
.SH AUTHOR
Function written by Loïc Le Guen and Yanis Leroy.

.SH COPYRIGHT
Free to use and modify for educational or personal purposes.